# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.35.1
# 

Name:       harbour-plants

# >> macros
%bcond_with harbour
# << macros
%define orgname s71e
%define appname plants
%define pkgname %{name}
%define plugindir %{_datadir}/%{name}/
%define please ignore this macro
# add missing macros in case we want to use cmake_build/install
%if 0%{?sailfishos_version} < 40600
%if 0%{?sailfishos_version} <= 40000
%define cmake_build %__cmake --build "."
%define cmake_install %make_install
%else
%define cmake_build %__cmake --build "." -j8 --verbose
%define cmake_install DESTDIR=%buildroot %__cmake --install .
%endif
%endif

Summary:    App for identifying plants through image analyzation
Version:    1.3.1.1
Release:    0
Group:      Applications
License:    Apache-2.0
URL:        https://github.com/nephros/ut-plants
Source0:    %{name}-%{version}.tar.gz
Source100:  harbour-plants.yaml
Requires:   libsailfishapp-launcher
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  cmake
BuildRequires:  intltool
BuildRequires:  sailfish-svg2png
BuildRequires:  desktop-file-utils
BuildRequires:  cmake

%description
%{summary}.

%if 0%{?_chum}
Title: Plants
Type: desktop-application
DeveloperLogin: patrickjane
Categories:
 - Science
 - Utility
Custom:
  Repo: %{url}
# GitHub:
PackageIcon: %{url}/master/icons/%{name}.svg
# Codeberg:
PackageIcon: %{url}/raw/branch/master/icons/svgs/%{name}.svg
Screenshots:
 - %{url}/raw/metadata/screenshots/screenshot1.png
 - %{url}/raw/metadata/screenshots/screenshot2.png
 - %{url}/raw/metadata/screenshots/screenshot3.png
Links:
  Homepage: %{url}
  Help: %{url}/discussions
  Bugtracker: %{url}/issues
  Donation: https://openrepos.net/donate
%endif


%define __provides_exclude_from %{plugindir}
%define please_also ignore this macro
%if %{with harbour}
%undefine vendor
%undefine _vendor
%undefine _chum
%endif
%if 0%{?harbour_validation:1}
BuildRequires: sdk-harbour-rpmvalidator
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
sed -i 's/"Plants"/"%{name}"/' CMakeLists.txt
sed -i 's/"plants.s710"/"%{orgname}.%{appname}"/' CMakeLists.txt
mv Plants.desktop.in %{name}.desktop.in
# << build pre

%cmake .  \
    -DCMAKE_INSTALL_PREFIX=%{_datadir} \
    -DQT_IMPORTS_DIR=%{plugindir}

%cmake_build

# >> build post
#%%make_build
# << build post

%install
# >> install pre
#%%make_install
# << install pre
%cmake_install

# >> install post
# fix some UBPort install peculiarities:
install -d %{buildroot}%{_datadir}/applications
mv %{buildroot}/%{name}.desktop %{buildroot}%{_datadir}/applications/%{name}.desktop
install -d %{buildroot}%{_datadir}/icons/hicolor/512x512/apps/
mv %{buildroot}/%{_datadir}/assets/logo.png %{buildroot}%{_datadir}/icons/hicolor/512x512/apps/%{name}.png
# mangle version info
#sed -i -e "s/unreleased/%{version}/" %{buildroot}%{_datadir}/%{name}/qml/%{name}.qml
# install .desktop file from source tag:
#install -d %{buildroot}/  %{buildroot}%{_datadir}/applications
#install -m 644 %desktopsrc %{buildroot}/%{_datadir}/applications

# generate some icons
#for size in 86 108 128 172 256 512 1024; do
#install -d %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/
#sailfish_svg2png -z 1.0 -f rgba -s 1 1 1 1 1 1 ${size} %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/ %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/
#done

# Edit the main .desktop file for Sailjail
desktop-file-edit  \
--set-key=Exec \
--set-value="/usr/bin/%{name}" \
--set-name="Plants" \
--set-icon=%{name} \
--set-key=X-Nemo-Application-Type \
--set-value=qt5 \
%{buildroot}%{_datadir}/applications/%{name}.desktop
printf '\n\n[X-Sailjail]\nOrganizationName=%{orgname}\nApplicationName=%{appname}\nPermissions=UserDirs;Internet\n' \
>> %{buildroot}%{_datadir}/applications/%{name}.desktop

# do not package documentation:
rm -rf %{buildroot}%{_docdir}
rm -rf %{buildroot}%{_mandir}
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%find_lang %{orgname}.%{appname}

%check
# >> check
# this is just here so we can include a clean section below:
%clean
%if 0%{?harbour_validation:1}
echo '=========== Checking for Harbour compatability.'
mkdir -p ~/rpmbuild/OTHER || :
find ~/rpmbuild/RPMS -type f -name %{name}-%{version}*.rpm -exec /usr/libexec/sdk-harbour-rpmvalidator/rpmvalidation.sh -d 0 --no-color {}  \; | tee ~/rpmbuild/OTHER/harbour-validator.log ||:
echo '=========== DONE checking for Harbour compatability.'
%else
echo '=========== NOT checking for Harbour compatability.'
%endif
# << check

%files -f %{orgname}.%{appname}.lang
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/*/*/apps/%{name}.png
 %{_datadir}/%{name}
# >> files
# << files
