# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.35.1
# 

Name:       harbour-plants

# >> macros
%bcond_with harbour
# << macros
%define orgname s710
%define appname plants
%define pkgname %{name}
%define plugindir %{_datadir}/%{name}/
%define please ignore this macro
# add missing macros in case we want to use cmake_build/install
%if 0%{?sailfishos_version} < 40600
%if 0%{?sailfishos_version} <= 40000
%define cmake_build %__cmake --build "."
%define cmake_install %make_install
%else
%define cmake_build %__cmake --build "." -j8 --verbose
%define cmake_install DESTDIR=%buildroot %__cmake --install .
%endif
%endif

Summary:    App for identifying plants through image analyzation
Version:    1.3.1
Release:    1.sfos
Group:      Applications
License:    MIT
URL:        https://github.com/nephros/ut-plants
Source0:    %{name}-%{version}.tar.gz
Source100:  harbour-plants.yaml
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  cmake
BuildRequires:  intltool
BuildRequires:  sailfish-svg2png
BuildRequires:  desktop-file-utils
BuildRequires:  cmake

%description
%{summary}.

%if 0%{?_chum}
Title: Plants
Type: desktop-application
DeveloperLogin: patrickjane
Categories:
 - Science
 - Utility
Custom:
  Repo: %{url}
# GitHub:
PackageIcon: %{url}/raw/branch/sfos/icons/%{name}-512.png
Screenshots:
 - %{url}/raw/metadata/screenshots/screenshot1.png
 - %{url}/raw/metadata/screenshots/screenshot2.png
 - %{url}/raw/metadata/screenshots/screenshot3.png
Links:
  Homepage: %{url}
  Help: %{url}/discussions
  Bugtracker: %{url}/issues
  Donation: https://openrepos.net/donate
%endif


%define please_also ignore this macro
%if %{with harbour}
%undefine vendor
%undefine _vendor
%undefine _chum
%endif
%if 0%{?harbour_validation:1}
BuildRequires: sdk-harbour-rpmvalidator
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
sed -i 's/"Plants"/"%{name}"/' CMakeLists.txt
sed -i 's/"plants.s710"/"%{orgname}.%{appname}"/' CMakeLists.txt
mv Plants.desktop.in %{name}.desktop.in
sh ./lang_conv.sh
# << build pre

%cmake .  \
    -DCMAKE_INSTALL_PREFIX=%{_datadir}

%cmake_build

# >> build post
#%%make_build
# << build post

%install
# >> install pre
#%%make_install
# << install pre
%cmake_install

# >> install post
# fix some UBPort install peculiarities:
install -d %{buildroot}%{_datadir}/applications
mv %{buildroot}/%{name}.desktop %{buildroot}%{_datadir}/applications/%{name}.desktop
rm -f %{buildroot}/%{_datadir}/assets/logo.png
# locale files:
#for fname in $(find %%{buildroot}/share -type f); do
#install -Dpm644 $fname %%{buildroot}/$fname
#done
rm -r %{buildroot}/share
# generate some icons
for size in 86 108 128 172 256 512; do
sailfish_svg2png -z 1.0 -f rgba -s 1 1 1 1 1 1 ${size} icons/svgs %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps
done


install -d %{buildroot}%{_bindir}/
install -m755 %{buildroot}/%{_datadir}/%{name} %{buildroot}%{_bindir}/%{name}
rm %{buildroot}/%{_datadir}/%{name}

# Edit the main .desktop file for Sailjail
desktop-file-edit  \
--set-key=Exec \
--set-value="%{name}" \
--set-name="Plants" \
--set-icon=%{name} \
--set-key=X-Nemo-Application-Type \
--set-value=silica-qt5 \
%{buildroot}%{_datadir}/applications/%{name}.desktop
printf '\n\n[X-Sailjail]\nOrganizationName=%{orgname}\nApplicationName=%{appname}\nPermissions=UserDirs;Camera;MediaIndexing;Internet\n' \
>> %{buildroot}%{_datadir}/applications/%{name}.desktop
# MyBackup
printf '\n\n[X-HarbourBackup]\nBackupConfigList=/apps/%{orgname}/%{appname}/\nBackupPathList=.local/share/%{orgname}/%{appname}/;.config/%{orgname}/%{appname}/\n' \
>> %{buildroot}%{_datadir}/applications/%{name}.desktop
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%check
# >> check
# this is just here so we can include a clean section below:
%clean
%if 0%{?harbour_validation:1}
echo '=========== Checking for Harbour compatability.'
mkdir -p ~/rpmbuild/OTHER || :
find ~/rpmbuild/RPMS -type f -name %{name}-%{version}*.rpm -exec /usr/libexec/sdk-harbour-rpmvalidator/rpmvalidation.sh -d 0 --no-color {}  \; | tee ~/rpmbuild/OTHER/harbour-validator.log ||:
echo '=========== DONE checking for Harbour compatability.'
%else
echo '=========== NOT checking for Harbour compatability.'
%endif
# << check

%files
%{_bindir}/*
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/*/*/apps/%{name}.png
# >> files
%if %{with harbour}
%exclude %{_datadir}/locale/*
%endif
# << files
